const postTypes = {
    LOAD_POSTS_LOADING:"LOAD_POSTS_LOADING",
    LOAD_POSTS_SUCCESS:"LOAD_POSTS_SUCCESS",
    LOAD_POSTS_ERROR:"LOAD_POSTS_ERROR",
    HIDE_SHOW_MODAL:"HIDE_SHOW_MODAL",
}

export default postTypes;