const userTypes ={
    LOAD_USERS_LOADING:"LOAD_USERS_LOADING",
    LOAD_USERS_SUCCESS:"LOAD_USERS_SUCCESS",
    LOAD_USERS_ERROR:"LOAD_USERS_ERROR",
    SET_ACTIVE_PAGE:"SET_ACTIVE_PAGE"
}

export default userTypes;